"""add ensembl_vep_variants table

Revision ID: e5ec70b0bcb1
Revises: f7796609f7aa
Create Date: 2026-03-15 11:07:14.691605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ec70b0bcb1'
down_revision: Union[str, Sequence[str], None] = 'f7796609f7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensembl_vep_variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rsid', sa.String(), nullable=False),
    sa.Column('chromosome', sa.String(length=5), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('ref_allele', sa.String(length=500), nullable=False),
    sa.Column('alt_alleles', sa.String(length=1000), nullable=False),
    sa.Column('variant_type', sa.String(length=20), nullable=True),
    sa.Column('minor_allele', sa.String(length=50), nullable=True),
    sa.Column('minor_allele_freq', sa.Float(), nullable=True),
    sa.Column('ancestral_allele', sa.String(length=500), nullable=True),
    sa.Column('clinical_significance', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('evidence', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('most_severe_consequence', sa.String(length=100), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('gene_symbol', sa.String(length=50), nullable=True),
    sa.Column('vep_data', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ensembl_vep_chr_pos', 'ensembl_vep_variants', ['chromosome', 'position'], unique=False)
    op.create_index(op.f('ix_ensembl_vep_variants_rsid'), 'ensembl_vep_variants', ['rsid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ensembl_vep_variants_rsid'), table_name='ensembl_vep_variants')
    op.drop_index('ix_ensembl_vep_chr_pos', table_name='ensembl_vep_variants')
    op.drop_table('ensembl_vep_variants')
    # ### end Alembic commands ###
