"""Add comprehensive genetic analysis tables

Revision ID: 13f1f6623d1c
Revises: e19067c6122a
Create Date: 2025-08-24 22:31:52.256690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f1f6623d1c'
down_revision: Union[str, Sequence[str], None] = 'e19067c6122a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
