"""add_bigquery_cache_columns

Revision ID: 574474eb5bbc
Revises: gnomad_tables_001
Create Date: 2026-03-14 12:33:50.627927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '574474eb5bbc'
down_revision: Union[str, Sequence[str], None] = 'gnomad_tables_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_variants_analysis_id'), table_name='analysis_variants')
    op.create_index(op.f('ix_analysis_variants_id'), 'analysis_variants', ['id'], unique=False)
    op.drop_constraint(op.f('annotation_source_configs_source_name_key'), 'annotation_source_configs', type_='unique')
    op.create_index(op.f('ix_annotation_source_configs_id'), 'annotation_source_configs', ['id'], unique=False)
    op.create_index(op.f('ix_category_rules_category'), 'category_rules', ['category'], unique=False)
    op.create_index(op.f('ix_category_rules_id'), 'category_rules', ['id'], unique=False)
    op.drop_constraint(op.f('clinvar_gene_stats_gene_key'), 'clinvar_gene_stats', type_='unique')
    op.create_index(op.f('ix_clinvar_gene_stats_id'), 'clinvar_gene_stats', ['id'], unique=False)
    op.drop_index(op.f('ix_gnomad_variants_chrom_pos_ref_alt'), table_name='gnomad_variants')
    op.create_index('ix_gnomad_variants_chrom_pos_ref_alt', 'gnomad_variants', ['chrom', 'pos', 'ref', 'alt'], unique=True)
    op.add_column('shared_variant_annotations', sa.Column('chembl_data', sa.JSON(), nullable=True))
    op.add_column('shared_variant_annotations', sa.Column('fda_drug_data', sa.JSON(), nullable=True))
    op.add_column('shared_variant_annotations', sa.Column('alphafold_data', sa.JSON(), nullable=True))
    op.alter_column('shared_variant_annotations', 'marker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_shared_variant_annotations_marker_id'), table_name='shared_variant_annotations')
    op.create_index('ix_shared_variant_annotations_marker_id', 'shared_variant_annotations', ['marker_id'], unique=False)
    op.drop_column('variant_annotations', 'clinvar_data')
    op.drop_column('variant_annotations', 'snpedia_data')
    op.drop_column('variant_annotations', 'pharmgkb_data')
    op.drop_column('variant_annotations', 'ensembl_data')
    op.drop_column('variant_annotations', 'annotated_at')
    op.drop_column('variant_annotations', 'annotation_status')
    op.drop_column('variant_annotations', 'litvar_data')
    op.drop_column('variant_annotations', 'api_calls_made')
    op.alter_column('variant_mappings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_variant_mappings_id'), 'variant_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_mappings_id'), table_name='variant_mappings')
    op.alter_column('variant_mappings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('variant_annotations', sa.Column('api_calls_made', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('litvar_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('annotation_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('annotated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('ensembl_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('pharmgkb_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('snpedia_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variant_annotations', sa.Column('clinvar_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_shared_variant_annotations_marker_id', table_name='shared_variant_annotations')
    op.create_index(op.f('ix_shared_variant_annotations_marker_id'), 'shared_variant_annotations', ['marker_id'], unique=True)
    op.alter_column('shared_variant_annotations', 'marker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('shared_variant_annotations', 'alphafold_data')
    op.drop_column('shared_variant_annotations', 'fda_drug_data')
    op.drop_column('shared_variant_annotations', 'chembl_data')
    op.drop_index('ix_gnomad_variants_chrom_pos_ref_alt', table_name='gnomad_variants')
    op.create_index(op.f('ix_gnomad_variants_chrom_pos_ref_alt'), 'gnomad_variants', ['chrom', 'pos', 'ref', 'alt'], unique=False)
    op.drop_index(op.f('ix_clinvar_gene_stats_id'), table_name='clinvar_gene_stats')
    op.create_unique_constraint(op.f('clinvar_gene_stats_gene_key'), 'clinvar_gene_stats', ['gene'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_category_rules_id'), table_name='category_rules')
    op.drop_index(op.f('ix_category_rules_category'), table_name='category_rules')
    op.drop_index(op.f('ix_annotation_source_configs_id'), table_name='annotation_source_configs')
    op.create_unique_constraint(op.f('annotation_source_configs_source_name_key'), 'annotation_source_configs', ['source_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_analysis_variants_id'), table_name='analysis_variants')
    op.create_index(op.f('ix_analysis_variants_analysis_id'), 'analysis_variants', ['analysis_id'], unique=False)
    # ### end Alembic commands ###
