"""Add variant annotations table for comprehensive API data storage

Revision ID: 67d1cfd07f3c
Revises: 9fa8121214d7
Create Date: 2025-08-25 14:34:12.879227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d1cfd07f3c'
down_revision: Union[str, Sequence[str], None] = '9fa8121214d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
