"""Add rare_mutations and uncommon_mutations tables

Revision ID: ac0a020bc538
Revises: 67d1cfd07f3c
Create Date: 2025-08-25 16:30:12.257789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0a020bc538'
down_revision: Union[str, Sequence[str], None] = '67d1cfd07f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
