"""Add cascade delete for genetic analysis relationships

Revision ID: e19067c6122a
Revises: 12314ad7b24a
Create Date: 2025-08-24 21:38:50.440704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19067c6122a'
down_revision: Union[str, Sequence[str], None] = '12314ad7b24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('drug_responses_analysis_id_fkey'), 'drug_responses', type_='foreignkey')
    op.create_foreign_key(None, 'drug_responses', 'genetic_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('genetic_variants_analysis_id_fkey'), 'genetic_variants', type_='foreignkey')
    op.create_foreign_key(None, 'genetic_variants', 'genetic_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('health_risks_analysis_id_fkey'), 'health_risks', type_='foreignkey')
    op.create_foreign_key(None, 'health_risks', 'genetic_analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_risks', type_='foreignkey')
    op.create_foreign_key(op.f('health_risks_analysis_id_fkey'), 'health_risks', 'genetic_analyses', ['analysis_id'], ['id'])
    op.drop_constraint(None, 'genetic_variants', type_='foreignkey')
    op.create_foreign_key(op.f('genetic_variants_analysis_id_fkey'), 'genetic_variants', 'genetic_analyses', ['analysis_id'], ['id'])
    op.drop_constraint(None, 'drug_responses', type_='foreignkey')
    op.create_foreign_key(op.f('drug_responses_analysis_id_fkey'), 'drug_responses', 'genetic_analyses', ['analysis_id'], ['id'])
    # ### end Alembic commands ###
