"""add ensembl_genes table

Revision ID: f7796609f7aa
Revises: 574474eb5bbc
Create Date: 2026-03-14 15:33:44.976007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7796609f7aa'
down_revision: Union[str, Sequence[str], None] = '574474eb5bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_variant_annotations_marker_id'), table_name='shared_variant_annotations')
    op.create_index(op.f('ix_shared_variant_annotations_marker_id'), 'shared_variant_annotations', ['marker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_variant_annotations_marker_id'), table_name='shared_variant_annotations')
    op.create_index(op.f('ix_shared_variant_annotations_marker_id'), 'shared_variant_annotations', ['marker_id'], unique=False)
    # ### end Alembic commands ###
